### PR TITLE
Fixes

### LINKED ISSUE #5: P0: Could not pass event PlayerMoveEvent to CivMenu v1.1.5 org.bukkit.event.EventException
2015-09-20 10:20:50 [ERROR] Could not pass event PlayerMoveEvent to CivMenu v1.1.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance to a null location
        at org.bukkit.Location.distanceSquared(Location.java:452) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.Location.distance(Location.java:439) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at vg.civcraft.mc.civmenu.TOSListener.playerMoveEvent(TOSListener.java:69) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 15 more

### PR DESCRIPTION
**Pull request by suirad**
This fixes Civcraft/CivMenu#5, Civcraft/CivMenu#6, Civcraft/CivMenu#8

I have tested all changes. 
- Spelling error corrected
- PlayerMoveEvent will not process a null location
- Respawning clears the old location, and the move event updates itself with the new location after respawn. This works after death, and also if the player is kicked while dead and respawns after a reconnect.

### CODE REVIEW

File: src/vg/civcraft/mc/civmenu/TOSListener.java [hunk 1]
```diff
@@ -66,13 +65,27 @@ public void run() {
...
+				event.setTo(from);
 			}
 		}
 	}
+	
+	@EventHandler
+	public void playerRespawnEvent(PlayerRespawnEvent e) {
+		Player p = e.getPlayer();
+		if (!TOSManager.isTermPlayer(p, "CivMenu Agreement")) {
+			locations.remove(p.getUniqueId());
```
Comment (Maxopoly) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: This means if someone kills himself, he can walk around freely after he respawns (until he gets kicked). Instead a new location should be inserted here, to which the players is bound (the respawn location).

Comment (suirad) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: Lines 68-72 correct that issue, and makes sure it doesn't happen.

File: src/vg/civcraft/mc/civmenu/TOSListener.java [hunk 2]
```diff
@@ -66,13 +65,27 @@ public void run() {
 	public void playerMoveEvent(PlayerMoveEvent event) {
 		Player p = event.getPlayer();
 		if (!TOSManager.isTermPlayer(p, "CivMenu Agreement")) {
-			if(event.getTo().distance(locations.get(p.getUniqueId())) > plugin.GetConfig().get("terms.MovementRange").getInt()){
+			Location from = locations.get(p.getUniqueId());
+			if (from == null){
+				from = event.getFrom();
+				locations.put(p.getUniqueId(), from);
```
Comment (Maxopoly) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: This does solve the NPE, but not the issue behind it of players managing to slip through the login listener. Do we have any idea what could have possibly caused that?

Comment (suirad) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: It actually solves both. So, when the old location is removed during the respawn event, this locations.get(p.getUniqueId());(line 68) will return null. The null check afterwards will update the location for that user with their new location(lines 69-71), preventing them from getting around the movement barrier by respawning.

Comment (Maxopoly) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: Yeah, but the original issue was that there were unregistered players who were not bound to any location somehow (different issue than the respawning), so there were NPE thrown all the time when it tried to get their bound location. Your solution completly solves the symptoms of the issue, I was just curious whether we know what caused it in the first place (I dont think so).

File: src/vg/civcraft/mc/civmenu/TOSListener.java (hunk 1 above)
Comment (Maxopoly) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: Ah yeah, it would be a bit clearer if it also readded it here, but overall it should work perfectly fine.

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
Can I even do that?

File: src/vg/civcraft/mc/civmenu/TOSListener.java (hunk 2 above)
Comment (idoash4) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: I doubt you can slip through the login listener. The problem is more likely be something with the sql manager returning false even though the player has already registered and was removed from the map.

Comment (suirad) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: Unregistered players not bound to any location should be caught by these changes. Reasons why that may happen i am not aware, as the login event handler is pretty plain. These changes should also catch the edge case of the player getting pearled before accepting the TOS, since it clears the old location.

File: src/vg/civcraft/mc/civmenu/TOSListener.java (hunk 1 above)
Comment (idoash4) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: I agree with Max it should be added here as well just to make the code more clear.

File: src/vg/civcraft/mc/civmenu/TOSListener.java (hunk 2 above)
Comment (idoash4) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:71]: Yeah this should fix many edge cases.

File: src/vg/civcraft/mc/civmenu/TOSListener.java (hunk 1 above)
Comment (suirad) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: Readding the location here does not seem to work properly(i found that by copy-pasting your pull manually) by my tests, for some reason. When the location was readded, it kept putting me inside blocks and suffocating me.

Comment (idoash4) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: Did you test it with random spawn installed on the server?

Comment (suirad) [inline src/vg/civcraft/mc/civmenu/TOSListener.java:85]: No. It's not the spawning itself that puts me inside blocks, its the teleport from the move event that does it. I had this right after line 85:

``` java
locations.put(p.getUniqueId(), e.getRespawnLocation());
```

With that added, the teleport when going too far puts you inside the ground. I am not sure why...

**Comment by suirad** [comment]
I already have #4 finished, should i just commit and pin it onto this pull or just wait until after this pull is merged so its separate?

**Comment by Maxopoly** [comment]
make a new branch, pull from civcraft's master into that branch, then do your changes and make a new pull request from that branch.

**Comment by suirad** [comment]
Sounds good.

**Comment by suirad** [comment]
This should be good to merge.

**Comment by ttk2** [comment]
ok doing so.
